# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
    

#Use Python 3.x
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7.6 
  displayName: 'Use Python 3.7.6'


#Creating Virtual Environments
- script:
   python -m pip install --upgrade pip
   python3 -m venv project
   source project/bin/activate
   pip3 install -r requirements.txt
   pip3 list
   deactivate
   

# install flask
- script:
   pip install Flask
   install python-virtualenv


- script: 
   pip install gunicorn
  displayName: 'install gunicorn'


#Install dependencies And requirements
- script: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt
        python -m pip install --upgrade pip
        sudo apt-get -y install nginx git
       
  displayName: 'Install enverionment'



#- script: |
  # pip install gunicorn 
   #gunicorn --bind=0.0.0.0:1742 --workers=4 hello:app
  #displayName: 'Install gunicorn tools '


  #run test
- script: python test_test1.py
  displayName: 'Pytest'


#Archive app
- task: ArchiveFiles@2
  displayName: 'Archive app'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    archiveFile: '$(Build.ArtifactStagingDirectory)$(Build.BuildId).zip'


- task: ArchiveFiles@2
  displayName: 'Archive tests'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    archiveFile: '$(Build.ArtifactStagingDirectory)$(Build.BuildId).zip'

       
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
    quiet: true

#Copy file

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'areenweb@40.87.8.185'
    contents: |
      requirements.txt
      run_sever.sh
      hello.py
    targetFolder: '/home/areenweb'
    readyTimeout: '20000'


- task: SSH@0
  inputs:
    sshEndpoint: 'areenweb@40.87.8.185'
    runOptions: 'commands'
    commands: |
      install python3-venv 
       install python3-pip 
      export FLASK=hello.py
    readyTimeout: '20000'



- task: ExtractFiles@1
  displayName: 'Extract files '
  inputs:
    destinationFolder: '$(System.DefaultWorkingDirectory)'
