# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

 # Environment name
  environmentName: '{{ webAppName }}'

#Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7.6 
  displayName: 'Use Python 3.7.6'

- script: |
         python -m venv antenv
         source antenv/bin/activate
         python -m pip install --upgrade pip
         pip install setup
         pip install -r requirements.txt


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(projectRoot)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true







    
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'areenweb@40.87.8.185'
    sourceFolder: 'hello_app/'
    contents: '**'
    targetFolder: '/home/areenweb/hello-app'
    readyTimeout: '20000'
    failOnEmptySource: true

  