# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


#deploy procsees
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.7.6 
  displayName: 'Use Python 3.7.6'
 
- script: |
         python -m venv antenv
         source antenv/bin/activate
         python -m pip install --upgrade pip
         pip install setup
         pip install -r requirements.txt
       
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true
    quiet: true

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'areenweb@40.87.8.185'
    sourceFolder: 'hello_app/'
    contents: '**'
    targetFolder: 'webapp.py'
    readyTimeout: '20000'
   
    


- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- task: SSH@0
  inputs:
    sshEndpoint: 'areenweb@40.87.8.185'
    runOptions: 'inline'
    inline: 'gunicorn --bind=0.0.0.0:1742020--workers=4 hello:app'
    readyTimeout: '20000'

    